server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://containers-us-west-87.railway.app:6838/railway
    username: postgres
    password: j8Gtwf6UWdmtCM9iiDV2

  #    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/hajzxjip
  #    username: hajzxjip
  #    password: UTJtqDWd_ZPsiNfmwAUxRzDhi3FPniuY

